GET http://localhost:3000/trainings/10
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjE5LCJlbWFpbCI6ImNvYWNoMTIzNDVAZXhhbXBsZS5jb20iLCJpYXQiOjE3NTM5NTgwNzQsImV4cCI6MTc1NDU2Mjg3NH0.IUk6bN9NMOXoVF_RRHJoEiz-T1V8Jin0sKgUkBrXdrg
Content-Type: application/json

