POST http://localhost:3000/users/register
Content-Type: application/json

{
  "email": "nocoach123@example.com",
  "password": "123456",
  "name": "Coach Max",
  "role": "client",
  "certificate": "Certified by FitPro",
  "description": "Тренирую людей более 5 лет",
  "location": "Москва",
  "trainingLevel": "advanced"
}
